# Site settings
remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Raul Santos"
description: "Director of Engineering | Building & Scaling High-Performance Engineering Teams"
baseurl:
url: https://occasionallyinsightful.com
logo:
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
twitter:
  username: Tecnico1931

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Search
search_full_content: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CHANGELOG.md
  - LICENSE
  - docs/
  - example/
  - banner.js
  - package.json
  - package-lock.json
  - Rakefile
  - "*.gemspec"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Site Author
author:
  name: "Raul Santos"
  picture:
  email:
  twitter: Tecnico1931
  links:
    - title: LinkedIn
      url: https://www.linkedin.com/in/raulesantos/
      icon: fab fa-linkedin
    - title: GitHub
      url: https://github.com/Tecnico1931
      icon: fab fa-github
    - title: Twitter
      url: https://twitter.com/Tecnico1931
      icon: fab fa-twitter

# Footer Links
footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/raulesantos/
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/Tecnico1931
    icon: fab fa-github
  - title: Twitter
    url: https://twitter.com/Tecnico1931
    icon: fab fa-twitter
